# Generated by Django 3.1.2 on 2021-03-02 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeeWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10)),
                ('word', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'beeword_tb',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickidx', models.IntegerField(default=0)),
                ('lastscore', models.BooleanField(default=False)),
                ('scoreboard_pass', models.IntegerField(default=0)),
                ('scoreboard_fail', models.IntegerField(default=0)),
                ('pickword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordscore', to='spellbee.beeword')),
            ],
        ),
    ]
