# Generated by Django 3.1.7 on 2021-03-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beeword',
            name='word',
            field=models.CharField(max_length=90, null=True, unique=True),
        ),
    ]
