# Generated by Django 3.1.7 on 2021-04-04 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spellbee', '0002_auto_20210318_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'managed': True},
        ),
        migrations.RenameField(
            model_name='score',
            old_name='scoreboard_fail',
            new_name='scoreboard',
        ),
        migrations.RemoveField(
            model_name='score',
            name='scoreboard_pass',
        ),
        migrations.AlterModelTable(
            name='beeword',
            table='Spellbeeword_tb',
        ),
        migrations.AlterModelTable(
            name='score',
            table='Spellbeeword_Score_tb',
        ),
        migrations.CreateModel(
            name='YearList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WOC_2021', models.IntegerField(default=0)),
                ('SOW_2021', models.IntegerField(default=0)),
                ('WOC_2020', models.IntegerField(default=0)),
                ('SOW_2020', models.IntegerField(default=0)),
                ('pickword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearlist', to='spellbee.beeword')),
            ],
        ),
    ]
