# Generated by Django 3.1.7 on 2021-04-11 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spellbee', '0005_auto_20210409_2126'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='beeword',
            table='spellbeeword_tb',
        ),
        migrations.AlterModelTable(
            name='score',
            table='spellbeeword_score_tb',
        ),
    ]
